tailor-cms/author

.github/actions/run/action.yml
.github/workflows/pr.yml
apps/backend/app.js
apps/backend/package.json
apps/backend/shared/mail/index.js
apps/frontend-nuxt/package.json
pnpm-lock.yaml
tests/api/client.ts
tests/playwright.config.ts

- Use nuxt build when serving prod statics
- Improve routing via connect-history-api-fallback
- Update CI config
- Cleanup

Use prod build for E2E

---

apps/backend/app.js
apps/backend/package.json
apps/backend/repository/repository.controller.js
apps/frontend/components/catalog/AddRepository/index.vue
apps/frontend/components/common/ConfirmationDialog.vue
apps/frontend/components/common/TailorDialog.vue
apps/frontend/pages/index.vue
pnpm-lock.yaml

- Remove AI toggle for import
- Fix catalog filter issue due to query string parsing issues
- Resolve import error (missing CB)
- Tweak UI
- Limit import filetypes
- Fix sorting when catalog is fully loaded

Catalog improvements

---

apps/frontend/components/repository/Outline/OutlineToolbar.vue
apps/frontend/components/repository/Outline/SearchResult.vue
apps/frontend/layouts/auth.vue
apps/frontend/pages/repository/[[id]].vue
apps/frontend/pages/repository/[[id]]/root.vue
apps/frontend/pages/repository/[[id]]/root/revisions.vue
apps/frontend/pages/repository/[[id]]/root/settings/general.vue
apps/frontend/pages/repository/[[id]]/root/structure.vue

- minor tweaks & cleanup of repository pages

Refine repository root

---

apps/frontend/pages/repository/[[id]]/root.vue
tests/playwright.config.ts
tests/specs/visual/catalog.spec.ts
tests/specs/visual/repository.spec.ts

- fix catalog snapshoting
- add repository structure snapshot
- add repository settings snapshot

Tweak visual tests

---

apps/frontend/components/editor/ActivityContent/ContainerList.vue
apps/frontend/components/editor/ActivityContent/index.vue
apps/frontend/components/editor/Sidebar/index.vue
apps/frontend/components/editor/Toolbar/index.vue
apps/frontend/pages/repository/[[id]]/editor.vue
packages/core-components-next/src/components/AddElement/AddNewElement.vue
packages/core-components-next/src/components/AddElement/InlineActivator.vue
packages/core-components-next/src/components/AddElement/index.vue
packages/core-components-next/src/components/ContentElement.vue
packages/core-components-next/src/components/Discussion/Thread/Comment/CommentHeader.vue
packages/core-components-next/src/components/Discussion/Thread/Comment/CommentPreview.vue
packages/core-components-next/src/components/Discussion/Thread/Comment/index.vue
packages/core-components-next/src/components/Discussion/index.vue
packages/core-components-next/src/components/ElementDiscussion.vue
packages/core-components-next/src/components/TailorTreeview/index.vue
packages/core-extensions/content-containers/page/src/edit/index.vue
tests/specs/visual/catalog.spec.ts
tests/specs/visual/repository.spec.ts

- Fix element insert position
- Fix element discussion issues
- Fix issues with editor sidebar expansion
- Tweak UI
- Fix issues with visual test diff

Refine editor

---

.github/actions/run/action.yml
extensions/content-elements/registry.json
package.json
pnpm-lock.yaml
scripts/boot.js
scripts/setup/database.js
scripts/setup/index.js
scripts/setup/user-prompts.js

- Ability for setup script to configure compose.dev based services
- Ability to opt in for seed
- Ability to run complete dev stack with single command

Simplify dev setup

---

apps/frontend/components/catalog/AddRepository/index.vue
apps/frontend/components/catalog/Filter/SearchInput.vue
apps/frontend/components/common/AppBar.vue
apps/frontend/layouts/auth.vue
apps/frontend/pages/index.vue

- Improve auth layout responsiveness
- Improve catalog responsiveness

Improve responsiveness

---

apps/frontend/nuxt.config.ts
scripts/boot.js

- Proxy .env configuration to NUXT

Ability to configure dev ports

---

tests/pom/repository/Outline.ts
tests/pom/repository/OutlineItem.ts
tests/specs/visual/editor.spec.ts

- Take a snapshot of the content editor page

Init editor visual testing

---

.env.example
apps/backend/shared/ai/ai.service.js
apps/frontend/pages/repository/[[id]]/editor.vue
infrastructure/Pulumi.dev.yaml
packages/core-components-next/src/components/TailorTreeview/index.vue
tests/pom/editor/Editor.ts
tests/pom/editor/Sidebar.ts
tests/specs/functional/editor/editor.spec.ts

- Expand if there are collapsed by default

Init editor functional testing

---

apps/frontend/components/common/ActivityOptions/ActivityMenu.vue
apps/frontend/components/repository/Outline/OutlineItem.vue
apps/frontend/pages/repository/[[id]]/root/structure.vue
tests/pom/repository/OutlineItem.ts
tests/specs/functional/repository/repository-structure.spec.ts

Improve e2e coverage

---

apps/frontend/components/repository/Sidebar/ActivityPublishing.vue
tests/pom/editor/Container.ts
tests/pom/repository/OutlineSidebar.ts
tests/specs/functional/editor/editor.spec.ts
tests/specs/functional/repository/repository-structure.spec.ts

- Activity meta update
- Publishing

Increase e2e coverage

---

apps/frontend/components/catalog/Filter/RepositoryFilter.vue

Add checkboxes to repository filters

---

apps/backend/activity/activity.controller.js
apps/backend/activity/activity.model.js
apps/backend/activity/status.model.js
apps/backend/content-element/content-element.model.js
apps/backend/repository/repository.controller.js
apps/backend/repository/repository.model.js
apps/backend/shared/logger.js
apps/backend/shared/publishing/helpers.js
apps/frontend/components/editor/Sidebar/ElementSidebar/ElementMeta/Relationships/RelationshipType.vue
apps/frontend/composables/usePublishActivity.ts
apps/frontend/pages/repository/[[id]]/root/settings.vue
apps/frontend/stores/content-elements.ts
packages/core-components-next/src/components/ContentPreview/index.vue

- Port [1120](https://github.com/ExtensionEngine/tailor/pull/1120), [1121](https://github.com/ExtensionEngine/tailor/pull/1121), [1126](https://github.com/ExtensionEngine/tailor/pull/1126), [1127](https://github.com/ExtensionEngine/tailor/pull/1127), [1137](https://github.com/ExtensionEngine/tailor/pull/1137), [1138](https://github.com/ExtensionEngine/tailor/pull/1138), [1132](https://github.com/ExtensionEngine/tailor/pull/1132)

Port Tailor src repository changes

---

apps/frontend/components/repository/Revisions/EntityRevisions.vue
apps/frontend/components/repository/Revisions/EntitySidebar.vue
apps/frontend/components/repository/Revisions/RevisionItem.vue
apps/frontend/pages/repository/[[id]]/root/revisions.vue
packages/core-components-next/src/components/ContainedContent.vue

This PR migrates Content Element Revision

Migrate Content Element Revision

---

.github/actions/run/action.yml
.github/actions/setup/action.yml
.github/workflows/deploy.yml
.github/workflows/docs.yml
Dockerfile
tests/api/SeedClient.ts
tests/helpers/seed.ts
tests/pom/common/utils.ts
tests/pom/editor/Editor.ts
tests/specs/functional/editor/editor.spec.ts
tests/specs/functional/repository/revision.spec.ts
tests/specs/functional/repository/structure.spec.ts
tests/specs/visual/editor.spec.ts
tests/specs/visual/repository.spec.ts

- Use generic outline level names to enable adaptability to different schemas

Cleanup E2E

---

packages/core-components-next/src/components/FileInput.vue
packages/core-components-next/src/components/TailorTreeview/ItemGroup.vue
packages/core-components-next/src/components/TailorTreeview/ListItem.vue
packages/core-extensions/meta-inputs/meta-file/src/EditMeta.vue

Adds thumb preview for fileinput component

Add thumb preview for FileInput

---

.env.example
apps/backend/activity/activity.controller.js
apps/backend/config/server/consumer.js
apps/backend/config/server/index.js
apps/backend/shared/oAuth2Provider.js
apps/backend/shared/publishing/publishing.service.js
docs/dev/general/setup.md

- Use existing oAuth client for securing the preview route

Use oauth2 for preview route

---

apps/backend/activity/activity.controller.js
apps/backend/repository/repository.controller.js
apps/backend/shared/publishing/helpers.js
apps/backend/shared/storage/helpers.js
apps/backend/shared/storage/providers/amazon.js
apps/backend/shared/storage/storage.service.js
packages/tailor-config-parser/src/schema-validation.js

- Replace mississipi through with node stream
- Fix preview url API call
- Port debug logging for export, publish and clone
- Support for deprecated Primitive CE
- Content Element Meta asset resolution
- Cleanup storage
- Update Meta label constraints

Misc tweaks

---

apps/frontend/components/editor/Toolbar/ActivityActions.vue

- Disable if there are not Content Elements
- Open in new page

Preview improvements

---

.github/workflows/pr.yml
apps/backend/app.js
apps/backend/router.js
infrastructure/src/index.ts

- Consolidate healthcheck route under /api (`/healthcheck` => `/api/healthcheck`)

Update healthcheck route & verify if app is running before initiating E2E

---

apps/backend/tests/api/seed.service.js
apps/frontend/components/editor/Sidebar/index.vue
apps/frontend/components/editor/Toolbar/index.vue
apps/frontend/components/repository/Workflow/Overview/index.vue
apps/frontend/components/repository/Workflow/Sidebar/SidebarBody.vue
apps/frontend/components/repository/Workflow/Sidebar/SidebarHeader.vue
apps/frontend/components/repository/Workflow/Sidebar/index.vue
apps/frontend/plugins/vuetify.ts
packages/core-extensions/meta-inputs/meta-color/src/EditMeta/ColorInput.vue
packages/core-extensions/meta-inputs/meta-color/src/EditMeta/index.vue

- Tweak editor sidebar
- Cleanup misc minors

Misc UI improvements

---

packages/core-components-next/src/components/ElementDiscussion.vue

- Mount discussion UI outside of container to avoid scroll / overflow

Avoid container UI overflow

---

apps/backend/shared/mail/index.js

- Log sent email
- Log email failure

Suppress email errors

---

apps/frontend/components/common/AppBar.vue
apps/frontend/components/editor/Sidebar/ElementSidebar/index.vue
apps/frontend/components/repository/Sidebar/index.vue

- Update sidebar error color
- Update appbar active state color

Minor UI improvements

---

apps/frontend/pages/auth/forgot-password.vue

- Should return to previous page instead of sign in page

Update back button route

---

apps/frontend/pages/repository/[[id]]/root/settings/general.vue
packages/core-components-next/src/components/FileInput.vue
packages/core-extensions/meta-inputs/meta-color/src/EditMeta/index.vue
packages/core-extensions/meta-inputs/meta-textarea/src/EditMeta.vue

- Improve label consistency
- Enable textarea row config

Tweak meta UI

---

apps/frontend/components/editor/Toolbar/DefaultToolbar.vue
apps/frontend/components/editor/Toolbar/ElementToolbar.vue
extensions/content-elements/package.json
pnpm-lock.yaml

This PR bumps ce html TE and tweaks toolbar to improve responsiveness

Bump ce-html, tweak toolbar

---

apps/frontend/stores/comments.ts

- Items are soft deleted & comment needs to be kept in store

Update comment upon delete

---

apps/backend/activity/activity.controller.js
apps/frontend/components/repository/Outline/CopyActivity/index.vue

- Update activity id resolution to a new mapping scheme
- Fix schema filtering

Address copy activity issues

---

extensions/content-elements/package.json
pnpm-lock.yaml

This PR bumps Multiple Choice content Element which solves issue causing element to break

Bump Multiple Choice Content Element 

---

apps/frontend/components/catalog/AddRepository/index.vue
packages/core-components-next/src/components/ContentElement.vue

Fix Default Values

---

apps/frontend/components/editor/Sidebar/ElementSidebar/ElementMeta/Relationships/index.vue
apps/frontend/stores/content-elements.ts

This PR updates editor store selectedElement upon element update

Update selected element

---

extensions/meta-inputs/client.js
extensions/meta-inputs/package.json
extensions/meta-inputs/registry.json
packages/core-extensions/meta-inputs/meta-select/package.json
packages/core-extensions/meta-inputs/meta-select/src/EditMeta.vue
packages/core-extensions/meta-inputs/meta-select/src/index.js
pnpm-lock.yaml

This PR migrates select meta input to v7. Solves #222

Migrate meta-select

---

extensions/meta-inputs/client.js
extensions/meta-inputs/package.json
extensions/meta-inputs/registry.json
packages/core-extensions/content-containers/page/package.json
packages/core-extensions/meta-inputs/meta-checkbox/package.json
packages/core-extensions/meta-inputs/meta-color/package.json
packages/core-extensions/meta-inputs/meta-combobox/package.json
packages/core-extensions/meta-inputs/meta-datetime/package.json
packages/core-extensions/meta-inputs/meta-datetime/src/EditMeta.vue
packages/core-extensions/meta-inputs/meta-datetime/src/index.js
packages/core-extensions/meta-inputs/meta-file/package.json
packages/core-extensions/meta-inputs/meta-html/package.json
packages/core-extensions/meta-inputs/meta-radio-group/package.json
packages/core-extensions/meta-inputs/meta-select/package.json
packages/core-extensions/meta-inputs/meta-switch/package.json
packages/core-extensions/meta-inputs/meta-textarea/package.json
pnpm-lock.yaml

This PR migrates datetime meta input to v7. Solves #221

Migrate meta-datetime

---

apps/backend/activity/activity.controller.js
apps/backend/content-element/content-element.model.js
apps/backend/repository/repository.model.js
apps/backend/shared/publishing/publishing.service.js
apps/backend/shared/transfer/default/processors.js

This PR:
- replaces throwing error with logging 
- fixes activity remapping
- remaps uid conditionally

FIx refs remapping

---

apps/backend/config/server/general.js

This PR tweaks backend filtering of the schemas to exclude schemas not defined by config

Tweak schema backend filtering

---

apps/frontend/pages/auth/index.vue
infrastructure/Pulumi.dev.yaml

This PR replaces Auth0 with Google Auth, updates oidc btn color

Replace Auth0 with Google Auth

---

apps/frontend/pages/auth/index.vue

Tweak Auth UI

---

extensions/content-elements/package.json
packages/core-components/package.json
packages/core-components/src/components/AddElement/AddNewElement.vue
packages/core-components/src/components/AssetInput.vue
packages/core-components/src/components/ElementPlaceholder.vue
packages/core-components/src/components/QuestionFeedback.vue
pnpm-lock.yaml

Adds spacing to asset input components, remove background from add element boxes, tweak colors

Update core components

---

apps/backend/repository/index.js

- Function receives roles as individual args

Fix issue with user role check

---

infrastructure/package.json
pnpm-lock.yaml

- Default pg v breaking change

Revert infra pkg version

---

.github/workflows/docs.yml
apps/frontend/components/repository/Settings/ExportModal.vue
tests/pom/repository/RepositorySettings.ts

- Disable export btn until ready
- Bump GH pages upload Action

Misc minors

---

.github/workflows/pr.yml
Dockerfile
docker-compose.dev.yaml
docker-compose.yaml

- Default spec was outdated
- Updated dev spec to avoid name collisions
- Added workflow job to test the default spec
- Minor tweaks

Update compose spec

---

apps/frontend/package.json
pnpm-lock.yaml

- Pin devtools due to breaking 2.X changes
- Bump nuxt core

Bump nuxt deps

---

.npmrc
apps/frontend/lib/SSEConnection.ts
apps/frontend/package.json
pnpm-lock.yaml

- Latest version of Nuxt works without hoisting

Cleanup npmrc

---

apps/backend/repository/repository.controller.js
apps/backend/shared/database/migrations/20250324114023-add-user-group-logo.js
apps/backend/user-group/index.js
apps/backend/user-group/user-group.controller.js
apps/backend/user-group/user-group.validation.js
apps/backend/user-group/userGroup.model.js
apps/frontend/components/admin/UserGroupDialog.vue
apps/frontend/components/common/AppBar.vue
apps/frontend/components/common/Avatar/index.vue
apps/frontend/components/common/UserGroupAvatar.vue
apps/frontend/pages/admin/user-groups/index.vue
apps/frontend/pages/index.vue
apps/frontend/pages/user/profile.vue
apps/frontend/stores/repository.ts
packages/tailor-interfaces/user-group.ts

- Ability to filter catalog by user group
- Ability to set user group logo

User group improvements

---

apps/frontend/pages/index.vue
apps/frontend/stores/repository.ts

- Reset catalog upon load instead of store removal
- Store removal might cause issues before redirect is completed

Update repository deletion handling

---

packages/core-components/src/components/AssessmentItem.vue
packages/core-components/src/components/QuestionElement.vue

This PR adds missing events to handle assessment items toggling

Fix toggling assessment items

---

apps/frontend/components/catalog/Card/Tags/AddTag.vue

- Enable only alphanumeric tags

Update tag validation

---

apps/frontend/components/catalog/Filter/RepositoryFilter.vue
apps/frontend/components/common/AppBar.vue
tests/pom/catalog/Catalog.ts
tests/specs/functional/catalog/catalog.spec.ts

This PR
- resets pagination when selecting user group
- fixes clicking on list checkbox

Fix catalog filtering

---

infrastructure/Pulumi.dev.yaml
infrastructure/src/env.ts
infrastructure/src/index.ts

- Optional image param (build and push image if not provided)
- Optional oidc setup params
- Optional ai config

Improve infra setup

---

packages/core-extensions/content-containers/page/src/edit/AIPrompt.vue
pnpm-workspace.yaml

This PR:
- fixes VCardActions typo
- adds content-elements to core-extensions

Port changes

---

.github/workflows/deploy.yml
infrastructure/src/env.ts

- Bump actions version
- Use get for optional config

Infra config improvements

---

apps/frontend/components/repository/Outline/CopyActivity/RepositoryTree.vue
packages/core-components/src/components/QuestionElement.vue
packages/core-components/src/components/SelectElement/SelectActivity.vue
tests/fixtures/auth.ts
tests/package.json
tests/pom/editor/SelectElementDialog.ts
tests/specs/functional/admin/user-group-list.spec.ts
tests/specs/functional/admin/user-management.spec.ts
tests/specs/functional/catalog/catalog.spec.ts
tests/specs/functional/common/user-profile.spec.ts
tests/specs/functional/repository/workflow.spec.ts

This PR fixes conditions for the processing activities when copying/linking

Fix copy activity

---

apps/frontend/plugins/vee-validate.ts

- Pass validation if value is null or undefined
- Should be handled by required flag

Update decimal validator
